name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Zip application for deployment
        run: zip -r app.zip .

      - name: Deploy to Azure Web App using ZipDeploy
        env:
          AZURE_DEPLOY_USERNAME: ${{ secrets.AZURE_DEPLOY_USERNAME }}
          AZURE_DEPLOY_PASSWORD: ${{ secrets.AZURE_DEPLOY_PASSWORD }}
        run: |
          curl -X POST \
            -u "$AZURE_DEPLOY_USERNAME:$AZURE_DEPLOY_PASSWORD" \
            --data-binary @app.zip \
            "https://sofia-hferg4bdeuekc3h7.scm.francecentral-01.azurewebsites.net/api/zipdeploy"
